Schema cleanup/refactor
CommonGateway/WooBundle pull request #36
Opened 2023-11-14 13:28 UTC by bbrands02

2023-11-15 14:34 UTC, rjzondervan approved these changes

2023-11-15 14:34 UTC, rjzondervan commented on Installation/Mapping/woo.xxllncCaseToWoo.mapping.json
> +    "themas.0.Hoofdthema": "unsetIfValue==",
Shouldn't this be themas.0.hoofdthema

2023-11-15 14:42 UTC, rjzondervan requested changes
Found a renamed object without renaming the cast

2023-11-15 14:58 UTC, rjzondervan approved these changes

2023-11-16 12:22 UTC, rjzondervan approved these changes

2023-11-16 12:54 UTC, WilcoLouwerse approved these changes

2023-11-16 12:54 UTC, WilcoLouwerse commented on Installation/Mapping/woo.xxllncDocumentToBijlage.mapping.json
>    }
Just checking, does this mapping not need any casts?

2023-11-16 12:54 UTC, WilcoLouwerse commented on Installation/Data/WooTestdata.json
> +      "id": "2023-002106",
Have you also tested this locally, this test data?
Does this work with the "id" field?
Doesn't the gateway try to set the ObjectEntity id with this value (which should be a uuid)?

2023-11-16 13:45 UTC, bbrands02 commented on Installation/Mapping/woo.xxllncDocumentToBijlage.mapping.json
>    }
no :)

2023-11-16 13:45 UTC, merged