Config option to only allow pdf
CommonGateway/WooBundle pull request #69
Opened 2024-03-06 16:22 UTC by bbrands02

2024-03-07 09:34 UTC, WilcoLouwerse requested changes

2024-03-07 09:34 UTC, WilcoLouwerse commented on Installation/Action/OpenWoo/woo.SyncAlbrandswaardOpenConvenantAction.action.json
> +        "allowPDFOnly": false,
Isn't this the default?
adding this isn't necessary if that is the case, else I would expect versions to be increased as well

2024-03-08 12:32 UTC, rjzondervan requested changes
Still missing the allowPDFOnly parameter in the action handler configuration options

2024-03-08 12:38 UTC, rjzondervan approved these changes

2024-03-08 13:05 UTC, WilcoLouwerse approved these changes

2024-03-08 13:05 UTC, WilcoLouwerse commented on README.md
> +* source (required): De reference van de source, die je meegeeft aan je source bij het aanmaken daarvan(bijv: `https://commongateway.woo.nl/source/example.zaaksysteem.source.json`).
daarvan _spatie_ (bijv

2024-03-08 13:31 UTC, WilcoLouwerse approved these changes

2024-03-08 13:32 UTC, merged