Config option to turn off auto publishing
CommonGateway/WooBundle pull request #70
Opened 2024-03-06 16:22 UTC by bbrands02

2024-03-07 07:51 UTC, rjzondervan requested changes

2024-03-07 07:51 UTC, rjzondervan commented on Installation/Schema/woo.publicatie.schema.json
> +        },
Don't forget to document your changes

2024-03-07 07:51 UTC, rjzondervan commented on src/Service/SyncOpenWooService.php
> +            'autoPublish' => $this->configuration['autoPublish'] ?? null,
Why not ?? true, we did refine that the default would be true.

2024-03-07 09:35 UTC, WilcoLouwerse requested changes

2024-03-07 09:35 UTC, WilcoLouwerse commented on Installation/Action/OpenWoo/woo.SyncAlbrandswaardOpenConvenantAction.action.json
> +        "autoPublish": true,
Shouldn't this be the default?
adding this isn't necessary if that is the case, else I would expect versions to be increased as well

2024-03-08 12:33 UTC, rjzondervan approved these changes

2024-03-08 13:33 UTC, merged