Connect Notubiz to Woo
CommonGateway/WooBundle pull request #83
Opened 2024-04-23 13:42 UTC by WilcoLouwerse

2024-04-23 14:32 UTC, bbrands02 commented on Installation/Source/woo.notubiz.source.json
> +        "callBody": true,
Beste callBody op false als met deze source bestanden gefetched worden (kan foutmeldingen veroorzaken bij sommige bestandtypes)

2024-04-23 14:39 UTC, WilcoLouwerse commented on Installation/Source/woo.notubiz.source.json
> +        "callBody": true,
Bedoel je niet de responseBody? die ik op false heb gezet, dat is waarom ik dit uberhaubt heb toegevoegd hier namelijk 😝

2024-04-23 14:40 UTC, bbrands02 commented on Installation/Source/woo.notubiz.source.json
> +        "callBody": true,
Hahahaha dat bedoelde ik inderdaad. Ff in de war

2024-04-23 14:41 UTC, bbrands02 approved these changes

2024-04-24 08:53 UTC, rjzondervan requested changes

2024-04-24 08:53 UTC, rjzondervan commented on src/Service/SyncNotubizService.php
> +    public function syncNotubizHandler(array $data, array $configuration): array
This is a rather complex function, are you sure there is no way to make it simpler (i.e. by splitting it into smaller functions)?

2024-04-25 08:04 UTC, WilcoLouwerse commented on src/Service/SyncNotubizService.php
> +    public function syncNotubizHandler(array $data, array $configuration): array
Will look into it

2024-05-07 06:52 UTC, rjzondervan approved these changes

2024-05-07 08:03 UTC, merged